SELECT * FROM mysql.user;
Select user, host from mysql.user;
Select * from mysql.help_topic;
select help_topic_id, help_category_id, url from mysql.help_topic;
show databases;
use fruits_db;
select database();
show databases;
use zillow;
select database();
use fruits_db;
select database();